// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOo-Q5gBzi3dVFm4boCRccbyhkpG_sYrA',
    appId: '1:248987056792:web:144b17eba0cded9b6eeeed',
    messagingSenderId: '248987056792',
    projectId: 'pdf-editor-e3a78',
    authDomain: 'pdf-editor-e3a78.firebaseapp.com',
    storageBucket: 'pdf-editor-e3a78.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzSQ9Rd0sl6dRxbYfXQlp7jtF5_SpQ43g',
    appId: '1:248987056792:android:6988b9788fe6d92a6eeeed',
    messagingSenderId: '248987056792',
    projectId: 'pdf-editor-e3a78',
    storageBucket: 'pdf-editor-e3a78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9HzRydyagIXHzEtw7cO73U6ysxQq_Wrs',
    appId: '1:248987056792:ios:9af48152bc99ca906eeeed',
    messagingSenderId: '248987056792',
    projectId: 'pdf-editor-e3a78',
    storageBucket: 'pdf-editor-e3a78.firebasestorage.app',
    iosBundleId: 'com.example.pdfEditor',
  );
}
